apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ecommerce-backend
build:
  local:
    push: false
  artifacts:
    - image: codewithajdotguru/gateway
      context: .
      docker:
        dockerfile: apps/gateway/Dockerfile
    - image: codewithajdotguru/products-app
      context: .
      docker:
        dockerfile: apps/products-app/Dockerfile
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - k8s/**/*.yaml
portForward:
  - resourceType: service
    resourceName: postgres-service
    namespace: default
    port: 5432
    localPort: 5432
