apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-app
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
        - name: products-app
          image: codewithajdotguru/products-app
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
